1. Vital Signs [Internet]. Cleveland Clinic. [cited 2020 May 20]. Available from: https://my.clevelandclinic.org/health/articles/10881-vital-signs
2. Laskowski-Jones L. Responding to trauma: Your priorities in the first hour. Nursing2020 Critical Care. 2009;4(1):35–41.
3. Chandler CF, Lane JS, Waxman KS. Seatbelt sign following blunt trauma is associated with increased incidence of abdominal injury. The American Surgeon. 1997;63(10):885–8.
4. Hooper N, Armstrong TJ. Hemorrhagic Shock. StatPearls [Internet]. 2019 [cited 2020 May 7]. Available from: https://www.ncbi.nlm.nih.gov/books/NBK470382/
5. Low Blood Pressure [Internet]. NIH National Heart Lung and Blood Institute. [cited 2020 May 7]. Available from: https://www.nhlbi.nih.gov/health-topics/low-blood-pressure
6. Richards JR, McGahan JP. Focused Assessment with Sonography in Trauma (FAST) in 2017: What Radiologists Can Learn. Radiology. 2017;283(1):30-48.
7. Zerra PE, Josephson CD. Delayed Hemolytic Transfusion Reactions [Internet]. In: Transfusion Medicine and Homeostasis (Third Edition). 2019 [cited 2020 May 18] Available from: https://www.sciencedirect.com/science/article/pii/B9780128137260000647
8. Proctor LT.  Blood and blood products: Transfusion reaction [Internet]. In: Complications in Anesthesia (Second edition). 2017 [cited 2020 May 18]. Available from: https://www.sciencedirect.com/science/article/pii/B9781416022152500545
9. Haram K, Svendsen E, Abildgaard U. The HELLP syndrome: Clinical issues and management. A Review [Internet]. U.S. National Library of Medicine; 2009 February 26 [cited 2020 May 20]. Available from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2654858/
10. HELLP Syndrome and Preeclampsia [Internet]. HELLP Syndrome and Preeclampsia | Michigan Medicine. [cited 2020 May 20]. Available from: https://www.uofmhealth.org/health-library/hw20560
11. HELLP Syndrome [Internet]. Preeclampsia Foundation [cited 2020 May 20]. Available from: https://www.preeclampsia.org/hellp-syndrome
12. Sepsis [Internet]. Mayo Clinic. [cited 2020 May 22]. Available from: https://www.mayoclinic.org/diseases-conditions/sepsis/symptoms-causes/syc-20351214
13. Suddock JT. Transfusion Reactions. StatPearls [Internet]. U.S. National Library of Medicine; 2019 [cited 2020 May 12]. Available from: https://www.ncbi.nlm.nih.gov/books/NBK482202/
14. Bridwell RE, Carius BM, Long B, Oliver JJ, Schmitz G. Sepsis in Pregnancy: Recognition and Resuscitation. West J Emerg Med [Internet]. 2019 Aug 6 [cited 2020 May 22]; 20(5). Available from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6754194/
15. Kidney Infection [Internet]. May Clinic. [cited 2020 May 22]. Available from: https://www.mayoclinic.org/diseases-conditions/kidney-infection/symptoms-causes/syc-20353387
16. Seladi-Schulman J. Symptoms of COVID-19 [Internet]. Healthline. 2020 [cited 2020 May 20]. Available from: https://www.healthline.com/health/coronavirus-symptoms
17. Symptoms of Coronavirus [Internet]. Centers for Disease Control and Prevention; 2020 [cited 2020 May 20]. Available from: https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html
18. Specimen Collection and Preparation [Internet].  Mayo Medical Laboratories [cited 2020 May 29]. Available at: http://a1.mayomedicallaboratories.com/webjc/attachments/102/2ee2f59-specimen-collection-and-preparation.pdf 
19. Echo Lumena Operator Manual. Immucor®. 2nd ed. Norcross, GA. 2019; pg. 1-2  
20. Capture-R [video]. Immucor®. 2017 Sep 21 [cited 2020 May 27]. Available from: https://www.youtube.com/watch?v=pbBlx4fnD0Y
21. Direct Antiglobulin Testing [Internet]. Grand Strand Health. [cited 2020 May 27]. Available from http://hca-grandstrand.policystat.com/policy/6197737
22. Hinrichs M, Keith MA. Serologic Method Review: Cold acid elution (ELU Kit II).  Immunology Journal of Blood Group Serology and Molecular Genetics [Internet]. 2014 [cited 2020 May 30]; 30(3). Available at: https://www.redcrossblood.org/content/dam/redcrossblood/immunohematology-journal/30_3_07.pdf
23. Coombs Test - Principle, Types, Procedure and Result Interpretation [Internet]. Microbiology Info.com. [cited 2020 May 27]. Available from: https://microbiologyinfo.com/coombs-test-principle-types-procedure-and-result-interpretation/
24. Al-Riyami AZ, Al-Hashmi S, Al-Arimi Z, Wadsworth LD, Al-Rawas A, Al-Khabori M, et al. Recognition, Investigation and Management of Acute Transfusion Reactions: Consensus guidelines for Oman [Internet]. Sultan Qaboos University medical journal. Sultan Qaboos University Medical Journal, College of Medicine & Health Sciences; 2014 [cited 2020 May 30]. Available from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4117654/
25. Clinlab Navigator [Internet]. ClinLabNavigator. [cited 2020 May 30]. Available from: http://www.clinlabnavigator.com/transfusion-reaction-workup.html
26. Schroeder P, Dickinson R. Transfusion Reaction Workup [Internet]. Madison College. [cited 2020 May 30]. Available from: http://faculty.madisoncollege.edu/mljensen/BloodBank/Lab_Manual/transfusion_reaction_workup.htm
27. Comprehensive Metabolic Panel (CMP) [Internet]. Medline Plus Medical Encyclopedia. 2020 March 24 [cited 2020 June 5]. Available from: https://medlineplus.gov/lab-tests/comprehensive-metabolic-panel-cmp/
28. Beckman Coulter [Internet]. Instructions for Use: ISE Reagents. 2019 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSAUH101111-EN_US/BAOSAUH101111?type=pdf
29. Beckman Coulter [Internet]. Instructions for Use: Bicarbonate. 2019 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X3710-EN_US/BAOSR6X3710?type=pdf
30. Beckman Coulter [Internet]. Instructions for Use: Glucose. 2019 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X2111-EN_US/BAOSR6X2111?type=pdf
31. Beckman Coulter [Internet]. Instructions for Use: Urea Nitrogen. 2019 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X3411-EN_US/BAOSR6X3411?type=pdf
32. Beckman Coulter [Internet]. Instructions for Use: Creatinine. 2019 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X7815-EN_US/BAOSR6X7815?type=pdf
33. Beckman Coulter [Internet]. Instructions for Use: Calcium. 2019 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X11713-EN_US/BAOSR6X11713?type=pdf
34. Beckman Coulter [Internet]. Instructions for Use: Total Protein. 2020 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X3211-EN_US/BAOSR6X3211?type=pdf
35. Beckman Coulter [Internet]. Instructions for Use: Albumin. 2020 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X0212-EN_US/BAOSR6X0212?type=pdf
36. Beckman Coulter [Internet]. Instructions for Use: Total Biliruin. 2020 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X1212-EN_US/BAOSR6X1212?type=pdf
37. Beckman Coulter [Internet]. Instructions for Use: ALT. 2019 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X0710-EN_US/BAOSR6X0710?type=pdf
38. Beckman Coulter [Internet]. Instructions for Use: AST. 2020 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X0909-EN_US/BAOSR6X0909?type=pdf
39. Beckman Coulter [Internet]. Instructions for Use: ALP. 2020 [cited 2020 June 4]. Available from: https://www.beckmancoulter.com/download/file/phxBAOSR6X0409-EN_US/BAOSR6X0409?type=pdf
40. Comprehensive Metabolic Panel [Internet]. University of Rochester Medical Center Health Encyclopedia [cited 2020 May 7]. Available from: https://www.urmc.rochester.edu/encyclopedia/content.aspx?contenttypeid=167&contentid=comprehensive_metabolic_panel 
41. Babiker M, Elrouf A, Amanullah M, Zaman GS. Interference of hemolysis in the estimation of plasma aspartate aminotransferase, potassium and phosphate [Internet]. Journal of Investigative Biochemistry. 2013 [cited 2020 June 5]. Available from: https://www.ajpbp.com/fulltext/61-1369152863.pdf 
42. Felson S. Bilirubin Test: High vs. Low Levels, Direct vs. Indirect [Internet]. WebMD. 2019 [cited 2020 June 5]. Available from: https://www.webmd.com/a-to-z-guides/bilirubin-test#1
43. Test ID: BILID Bilirubin Direct, Serum [Internet]. Mayo Clinic Laboratories. [cited 2020 June 5]. Available from: https://www.mayocliniclabs.com/test-catalog/Clinical and Interpretive/81787
44. What are the different types of bilirubin? [Internet]. WebMD. 2017 Jan 25 [cited 2020 June 5]. Available from: https://www.webmd.com/a-to-z-guides/qa/what-are-the-different-types-of-bilirubin
45. Direct Bilirubin [Internet]. Beckmancoulter.com. 2020 [cited 5 June 2020]. Available from: https://www.beckmancoulter.com/wsrportal/techdocs?docname=/cis/BAOSR6x181/%25%25/EN_DIRECT%20BILIRUBIN.pdf
46. Shih AWY, McFarlane A, Verhovsek, M. Haptoglobin testing in hemolysis: Measurement and interpretation. American Journal of Hematology [Internet]. 2013 [cited 2020 June 2]; doi.org/10.1002/ajh.23623
47. Shim BS, Jue DM. Simple spectrophotometric determination of haptoglobin level in serum. Clinica Chimica Acta. 1984;136:145-153.
48. Wilczynski C. Haptoglobin [Internet]. Medscape. 2019 Nov 20 [cited 2020 June 2]. Available from: https://emedicine.medscape.com/article/2085592-overview#a1
49. Bhagavan NV, Ha C-E. Carbohydrate Metabolism I: Glycolysis and the Tricarboxylic Acid Cycle. In: Essentials of Medical Biochemistry (Second Edition). 2015:165-185.
50. Kato GJ, McGowan V, Machado RF, Little JA, Taylor J, Morris CR, Nichols JS, Wang X, Poljakovic M, Morris SM, Gladwin MT. Lactate dehydrogenase as a biomarker of hemolysis-associated nitric oxide resistance, priapism, leg ulceration, pulmonary hypertension, and death in patients with sickle cell disease. Blood. 2006; 107(6):2279-2285.
51. Barnett H. The staining of lactate dehydrogenase isoenzymes after electrophoretic saturation on cellulose acetate. Journal of Clinical Pathology. 1964;17:567-570.
52. Marshall T, Williams J, Williams KM. Electrophoresis of serum isoenzymes and proteins following acute myocardial infarction. Journal of Chromatography. 1991;569:323-345.
53. Vanderlinde RE.  Measurement of total lactate dehydrogenase activity. Annals of Clinical and Laboratory Science. 1985;15(1):13-31.
54. Lactate Dehydrogenase (LD) Isoenzymes [Internet]. Labcorp. 2020 [cited 6 June 2020]. Available from: https://www.labcorp.com/tests/001842/lactate-dehydrogenase-ld-isoenzymes
55. Higgins C. Lactate and Lactic Acidosis [Internet]. Acute Care Testing. 2007 Oct [cited 2020 June 6]. Available from: https://acutecaretesting.org/en/articles/lactate-and-lactic-acidosis
56. Bakker J. Increased blood lactate levels: a marker of ...? [Internet]. Acute Care Testing. 2003 [cited 2020 June 6]. Available from: https://acutecaretesting.org/en/articles/increased-blood-lactate-levels-a-marker-of/?src=lactate-2
57. Lee SM, An WS. New clinical criteria for septic shock: serum lactate level as new emerging vital sign. Journal of Thoracic Disease [Internet]. 2016 Jul [cited 2020 June 6];8(7):1388-90. doi: 10.21037/jtd.2016.05.55
58. Evaluating and Testing Persons for Coronavirus Disease 2019 (COVID-19) [Internet]. Centers for Disease Control and Prevention; 2020 [cited 2020 June 6]. Available from: https://www.cdc.gov/coronavirus/2019-nCoV/hcp/clinical-criteria.html
59. Coronavirus disease 19 (COVID-19) [Internet]. CDC Centers for Disease Control [cited 2020 June 9]. Available from: https://www.cdc.gov/coronavirus/2019-ncov/cdcresponse/index.html
60. BD BioGX SARS-CoV-2 Reagents for BD MAX System. Ref. 444213 [Internet]. BD.com [cited 2020 June 11]. Available from: https://www.bd.com/en-us/offerings/capabilities/molecular-diagnostics/molecular-tests/biogx-sars-cov-2-reagents
61. How Taqman assays work [Internet]. ThermoFisher Scientific [cited 2020 June 11]. Available from: https://www.thermofisher.com/us/en/home/life-science/pcr/real-time-pcr/real-time-pcr-learning-center/real-time-pcr-basics/how-taqman-assays-work.html
62. Rohner P, Pepey B, Aukenthaler R. Comparison of BacT/Alert with Signal Blood Culture System [Internet]. Journal of Clinical Microbiology. 1995 [cited 2020 June 9]. Available from: https://jcm.asm.org/content/jcm/33/2/313.full.pdf
63. BacT/ALERT®BPA [Internet]. bioMérieux, Inc. 2010 [cited 2020 June 9]. Available from: https://www.mycts.org/Portals/0/Assay_PI/CQC/BacT%20ALERT.pdf
64. Turan DB, Kuruoglu T, Gumus D, Kalayci F, Serefhanoglu K. Evaluation of Factors that may Cause False Positive Growth Signals in Blood Cultures [Internet]. International Journal of Clinical & Medical Microbiology. 2018 [cited 2020 June 13];3:137. Available from: https://www.graphyonline.com/archives/IJCMM/2018/IJCMM-137/article.pdf
65. Novak-Weekley S, Marlowe E, Poulter M, Dwyer D, Speers D, Rawlinson W et al. Evaluation of the Cepheid Xpert Flu Assay for Rapid Identification and Differentiation of Influenza A, Influenza A 2009 H1N1, and Influenza B Viruses. Journal of Clinical Microbiology. 2012;50(5):1704-1710.
66. GeneXpert Xpress [Internet]. p.widencdn.net. 2020 [cited 2020 June 12]. Available from: https://p.widencdn.net/lniiu1/Cepheid-GeneXpert-Xpress-System-Brochure-US-IVD-0688-English
67. Cepheid | Xpert Xpress Flu/RSV [Internet]. 2020 [cited 2020 June 13]. Available from: https://www.cepheidlegacy.com/uk/cepheid-solutions/clinical-ivd-tests/critical-infectious-diseases/xpert-xpress-flu-rsv
68. Keohane EM, Walenga JM, Otto CN. Rodak's Hematology: Clinical Principles and Applications. 6th ed. St. Louis: Elsevier; 2020. 
69. Hematek 3000 System [Internet]. Siemens Healthineers [cited 2020 June 17]. Available from: https://www.siemens-healthineers.com/hematology/systems/hematek-3000
70. Phillips J, Henderson AC. Hemolytic Anemia: Evaluation and Differential Diagnosis [Internet]. American Family Physician. 2018 Sept 15 [cited 2020 June 20];98:6. Available from: https://www.aafp.org/afp/2018/0915/p354.html#afp20180915p354-t3
71. Strobel E. Hemolytic Transfusion Reactions. Transfusion Medicine and Hemotherapy 2008;35:346-353.
72. Clinitek Urinalysis Point of Care Testing [Internet]. Aria Health. [cited 2020 June 20]. Available from: http://www.pointofcare.net/procedures/AriaHealth1209/ClinitekPOCUrinalysisTesting.pdf
73. Urine Studies [Internet]. Basic Medical Key [cited 2020 June 20]. Available from: https://basicmedicalkey.com/urine-studies/
74. SynthASil [Internet]. Instrumentation Laboratory. 2017 [cited 2020 June 17]. Available from: https://international.werfen.com/sitecore/content/il/products-services/hemostasis-diagnostics/reagents.aspx
75. RecombilPlasTin 2G [Internet]. Instrumentation Laboratory. 2019 [cited 2020 June 17]. Available from: https://international.werfen.com/sitecore/content/il/products-services/hemostasis-diagnostics/reagents.aspx
76. D-Dimer HS 500 [Internet]. Instrumentation Laboratory. 2018 [cited 2020 June 17]. Available from: https://international.werfen.com/sitecore/content/il/products-services/hemostasis-diagnostics/reagents.aspx
77. Arora S, Kolte S, Dhupia JS. Hemolyzed Samples Should be Processed for Coagulation Studies: The Study of Hemolysis Effects on Coagulation Parameters [Internet]. U.S. National Library of Medicine; 2014 [cited 2020 June 17]. Available from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3991946/
78. Padden MO. HELLP Syndrome: Recognition and Perinatal Management [Internet]. American Academy of Family Physician; 1999 [cited 2020 June 17]. Available from: https://www.aafp.org/afp/1999/0901/p829.html
79. Wilkinson DS. Clinical Utility of Genotyping Human Erythrocyte Antigens; 2016 April 14 [Internet]. U.S. National Library of Medicine [cited 2020 June 23]. Available from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4985764/#lmw014-B4
80. Nathalang O, Intharanut K, Siriphanthong K, Nathalang S, Kupatawintu P. Duffy Blood Group Genotyping in Thai Blood Donors. Annals of Laboratory Medicine 2015; 35(6):618-623.  
81. Shah A, Patel P, Patel K, Patel B, Jariwala K, Sharma P, Mishra K, Ghosh K. Comparison of serology and molecular detection of common red cell antigens in multitransfused thalassemia major and sickle cell disease patients. Transfusion and Apheresis Science. 2020; 59(1):102599.
82. Shin K-H, Lee H-J, Kim H-H, Hong YJ, Park KU, Kim MJ, Kwon J-R, Choi Y-S, Kim JN. Frequency of red blood cell antigens according to parent ethnicity in Korea using molecular typing. Annals of Laboratory Medicine. 2018;38(6):599-603.
83. Woodring TS, Farrell JJ. Pseudomonas poae-Associated Fatal Septic Transfusion Reaction, Peoria, Illinois, USA, 2017 [Internet]. Emerging Infectious Diseases. 2019 Aug [cited 2020 June 28];25(8):1445-1451. Available from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6649322/
84. Kinney SN, Slayten J, Waxman DA. Need for Education in Molecular Immunohematology: A Survey of Specialists in Blood Banking [Internet]. OUP Academic. Oxford University Press; 2016 [cited 2020 June 28]. Available from: https://doi.org/10.1093/labmed/lmw042
85. Schroeder P. Fetal Bleed Screening Test [Internet]. Madison College. 2002 February [cited 2020 July 7]. Available from: http://faculty.madisoncollege.edu/mljensen/BloodBank/Lab_Manual/fetal_bleed_screening_test.htm
86. Aldarweesh FA. The Duffy Blood Group System [Internet]. IntechOpen. 2019 October 29 [cited 2020 July 7]. Available from: https://www.intechopen.com/online-first/the-duffy-blood-group-system
87. Herndon JR. Cordocentesis Test for Diagnosing Fetal Abnormalities [Internet]. Verywell Family. 2019 August 4 [cited 2020 July 7]. Available from: https://www.verywellfamily.com/cordocentesis-4175008
88. Delaney M, Wendel S, Bercovitz RS, Cid J, Cohn C, Dunbar NM, Apelseth TO, Popovsky M, Stanworth SJ, Tinmouth A, Van De Watering L, Waters JH, Yazer M, Ziman A. Transfusion reactions: prevention, diagnosis, and treatment [Internet]. The Lancet. 2016 Dec 3-9 [cited 2020 July 12]; 388(10061):2825-2836. Available from: https://www.sciencedirect.com/science/article/pii/S0140673615013136
89. Irani MS, Karafin MS, Ernster L. Red cell exchange to mitigate a delayed hemolytic transfusion reaction in a patient transfused with incompatible red blood cells [Internet]. Journal of Clinical Apheresis. 2016 April 26 [cited 2020 July 12]. Available from: https://onlinelibrary.wiley.com/doi/full/10.1002/jca.21461 
90. Korsak J, Piotrowska A. Post-Transfusion Haemolytic Reactions [Internet]. IntechOpen. 2020 March 3 [cited 2020 July 12]. Available from: https://www.intechopen.com/online-first/post-transfusion-haemolytic-reactions
91. Prenatal Immunohematologic Testing [Internet]. Clinlabnavigator.com. 2020 [cited 2020 July 9]. Available from: http://www.clinlabnavigator.com/prenatal-immunohematologic-testing.html
92. Harewood J, Master SR. Hemolytic Transfusion Reaction. [Updated 2019 Jun 4]. StatPearls [Internet]. U.S. National Library of Medicine; 2019 [cited 2020 May 13]. Available from: https://www.ncbi.nlm.nih.gov/books/NBK448158/
93. Monitoring blood safety [Internet]. CDC – Centers for Disease Control and Prevention [cited 2020 July 3]. Available from: https://www.cdc.gov/bloodsafety/monitoring/blood_safety.html
94. Transfusion/Donation fatalities [Internet]. FDA – U.S. Food and Drug Administration [cited 2020 July 3]. Available from: https://www.fda.gov/vaccines-blood-biologics/report-problem-center-biologics-evaluation-research/transfusiondonation-fatalities
95. Fatalities Reported to FDA Following Blood Collection and Transfusion [Internet]. FDA – U.S. Food and Drug Administration [cited 2020 July 3].  Available from: https://www.fda.gov/media/136907/download
96. Vamvakas EC, Blajchman MA. Transfusion-related mortality: the ongoing risks of allogeneic blood transfusion and the available strategies for their prevention. Blood 2009;113(15):3406-3417.
97. Blumberg N, Heal JM. Mortality Risks, Costs, and Decision Making in Transfusion Medicine. American Journal of Clinical Pathology 2000;114:934-937.
98. Ribed-Sánchez B, González-Gaya C, Varea-Díaz S, Corbacho-Fabregat C, Bule-Farto I, Pérez de-Oteyzacf J.  Gaceta Sanitaria 2018;32(3):269-274.
99. Blackall D, Kaliner MA. Alloimmunization From Transfusions [Internet]. Medscape. 2017 Sept 8 [cited 2020 July 4]. Available from: https://emedicine.medscape.com/article/134958-overview#a6
100. Dumas G, Habibi A, Onimus T, Merle J, Razazi K, Dessap AM, Galactéros F, Michel M, Bacchi VF, Pirenne FN, Bartolucci P. Eculizumab salvage therapy for delayed hemolysis transfusion reaction in sickle cell disease patients [Internet]. The American Society of Hematology. 2016 February 25 [cited 2020 July 15]. Available from: https://ashpublications.org/blood/article/127/8/1062/35130/Eculizumab-salvage-therapy-for-delayed-hemolysis
101. Thein SL, Pirenne F, Fasano RM, Habibi A, Bartolucci P, Chonat S, et al. Hemolytic transfusion reactions in sickle cell disease: underappreciated and potentially fatal [Internet]. 2020 [cited 2020 July 17]. Available from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7049330/
102. Adkins BD, Sharma D, Eichbaum Q. Can we better predict delayed hemolytic transfusion reactions and hyperhemolysis in sickle cell disease? Transfusion and Apheresis Science. 2020;59:102681. 
103. Narbey D, Habibi A, Chadebech P, Mekontso-Dessap A, Khellaf M, Levievre JD, Godeau B, Michel M, Galacteros F, Djoudi R, Bartolucci P, Pirenne F. Incidence and predictive score for delayed hemolytic transfusion reaction in adult patients with sickle cell disease [Internet]. American Journal of Hematology. 2017 Sept 19 [cited 2020 July 4]. Available from https://onlinelibrary.wiley.com/doi/full/10.1002/ajh.24908
104. Pirenne F, Yazdanbakhsh K. How I safely transfuse patients with sickle-cell disease and manage delayed hemolytic transfusion reactions. Blood 2018;131(25):2773–81.
105. Gersten T, Zieve D, Conaway B, editors. Hemolytic transfusion reaction [Internet]. MedlinePlus Medical Encyclopedia; 2019 [cited 2020 May 7]. Available from: https://medlineplus.gov/ency/article/001303.htm
106. The American Red Cross. Blood Needs & Blood Supply; 2020 [cited 2020 May 13]. Available from: https://www.redcrossblood.org/donate-blood/how-to-donate/how-blood-donations-help/blood-needs-blood-supply.html
107. Vamvakas EC, Blajchman MA. Transfusion-related mortality: the ongoing risks of allogeneic blood transfusion and the available strategies for their prevention [Internet]. UCLA Pathology and Laboratory Medicine; 2011 [cited 2020 May 14]. Available from: http://pathology.ucla.edu/workfiles/Education/Transfusion%20Medicine/10-8-VamvakasBloodTransfusionMortality.pdf
108. Transfusion/Donation Fatalities [Internet]. U.S. Food & Drug Administration [cited 2020 May 14]. Available from: https://www.fda.gov/vaccines-blood-biologics/report-problem-center-biologics-evaluation-research/transfusiondonation-fatalities
109. Harmening D. Modern blood banking & transfusion practices. 7th ed. Philadelphia: F.A. Davis Company; 2019.
110. Department of Pathology - Blood Bank [Internet]. University of Michigan Department of Pathology. 2020 [cited 2020 July 2]. Available from: https://www.pathology.med.umich.edu/blood-bank/adverse-reactions-to-transfusion
111. Transfusion Reactions: Symptoms, Causes, & Complications [Internet]. Healthline. 2020 [cited 2020 July 2]. Available from: https://www.healthline.com/health/transfusion-reaction-hemolytic#complications
